-- CREAZIONE SCHEMA
CREATE USER indago_user IDENTIFIED BY indagoUserPassword;

-- GRANT
GRANT CONNECT, RESOURCE TO indago_user;

ALTER USER indago_user QUOTA UNLIMITED ON users;

-- SELECT username FROM all_users;

-- SELECT username, default_tablespace FROM dba_users WHERE username = 'INDAGO_USER';

/* SEMBRA CHE NON SERVI LA CREAZIONE DEL TABLESPACE*/
/*CREATE TABLESPACE indago_tablespace
    DATAFILE '/opt/oracle/oradata/ORCLCDB/orclpdb1/indago_tablespace01.dbf'
    SIZE 100M
    AUTOEXTEND ON
    NEXT 10M MAXSIZE 500M;*/
-- SELECT TABLESPACE_NAME FROM DBA_TABLESPACES -- WHERE TABLESPACE_NAME = 'INDAGO_TABLESPACE';
-- ALTER USER indago_user DEFAULT TABLESPACE INDAGO_TABLESPACE;
-- ALTER USER indago_user QUOTA UNLIMITED ON INDAGO_TABLESPACE;

/*SELECT USERNAME, TABLESPACE_NAME, BYTES
FROM DBA_TS_QUOTAS
WHERE USERNAME = 'INDAGO_USER';*/
--------
    -- CREAZIONI TABELLE
-----
-- INIZIALIZZAZIONE
/*

SELECT 'DROP TABLE ' || table_name || ' CASCADE CONSTRAINTS PURGE;'
FROM dba_tables
WHERE owner = 'INDAGO_USER';

-- Risultato
DROP TABLE PROFILO CASCADE CONSTRAINTS PURGE;
DROP TABLE UTENTE CASCADE CONSTRAINTS PURGE;
DROP TABLE STATO_FILE CASCADE CONSTRAINTS PURGE;
DROP TABLE FILE_UPLOAD CASCADE CONSTRAINTS PURGE;
DROP TABLE LOG_ERRORE_FILE CASCADE CONSTRAINTS PURGE;

*/


-- TABELLA PROFILI
CREATE TABLE indago_user.profilo
(
    id_profilo  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descrizione VARCHAR2(50) NOT NULL
);

-- TABELLA utenti
CREATE TABLE indago_user.utente
(
    id_utente      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR2(100)       NOT NULL,
    cognome        VARCHAR2(100)       NOT NULL,
    cod_fiscale    VARCHAR2(16) UNIQUE NOT NULL,
    id_profilo     NUMBER              NOT NULL,
    data_creazione DATE DEFAULT SYSDATE/*,
    FOREIGN KEY (id_profilo) REFERENCES indago_user.profilo (id_profilo)*/
);


CREATE TABLE indago_user.stato_file
(
    id_stato    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descrizione VARCHAR2(50) NOT NULL
);

CREATE TABLE indago_user.file_upload
(
    id_file          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_file        VARCHAR2(255) NOT NULL,
    file_contenuto   BLOB, -- Campo per contenere il file
    numero_errori    NUMBER DEFAULT 0,
    id_utente        NUMBER        NOT NULL,
    id_stato         NUMBER        NOT NULL,
    data_caricamento DATE DEFAULT SYSDATE/*,
    FOREIGN KEY (id_utente) REFERENCES indago_user.utente(id_utente),
    FOREIGN KEY (id_stato) REFERENCES indago_user.stato_file(id_stato)*/
);


CREATE TABLE indago_user.log_errore_file
(
    id_log             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_file            NUMBER         NOT NULL,
    errore_descrizione VARCHAR2(1000) NOT NULL/*,
    FOREIGN KEY (id_file) REFERENCES indago_user.file_upload (id_file)*/
);

CREATE TABLE indago_user.log_errore_openmetadata
(
    id_log             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_file            NUMBER         NOT NULL,
    errore_descrizione VARCHAR2(1000) NOT NULL/*,
    FOREIGN KEY (id_file) REFERENCES indago_user.file_upload (id_file)*/
);

/*
INSERIMENTO RIGHE DI DEFAULT
*/

INSERT INTO indago_user.profilo (descrizione)
VALUES ('viewer');
INSERT INTO indago_user.profilo (descrizione)
VALUES ('admin');

INSERT INTO indago_user.utente (nome, cognome, cod_fiscale, id_profilo)
VALUES ('Viewer', 'Test', 'viewrtest', 1);
INSERT INTO indago_user.utente (nome, cognome, cod_fiscale, id_profilo)
VALUES ('Admin', 'Test', 'admintest', 2);

-- FILE
INSERT INTO indago_user.stato_file (descrizione)
VALUES ('In elaborazione');
INSERT INTO indago_user.stato_file (descrizione)
VALUES ('Completato');
INSERT INTO indago_user.stato_file (descrizione)
VALUES ('In errore');
commit ;
